### ISSUE TITLE
Suddenly stopped working on 13.11.2020

### ISSUE THREAD

**Issue by zuck3r** [kalvn/shaarli2mastodon#11]
First I thought its because of a mastodon-server-update, but I've tried it with accounts on instances with v3.2.1 and v3.2.0:
nothing.

Now I've updated to shaarli 12.1:
everything works, but not this plugin.

Any idea?
Would be so great! :)

**Comment by kalvn** [comment]
Thanks for the feedback. I'll take a look soon, sorry for the delay.

**Comment by kalvn** [comment]
The last release (v2.0.1) should work fine with Shaarli 0.12.1.
