### ISSUE TITLE
Allow customization of the toot length

### ISSUE THREAD

**Issue by ewenewen** [kalvn/shaarli2mastodon#12]
I am using Shaarli and Shaarli2mastodon with my Pleroma instance, where the default toot/status length is much higher than 500 characters.
Would it be possible to add an editable parameter to change the toot length?

**Comment by kalvn** [comment]
This is now available in the last beta version : https://github.com/kalvn/shaarli2mastodon/releases/tag/v3.0.0-beta1

Would you like to give a try let me know if it works as expected?

**Comment by ewenewen** [comment]
Yes, it works perfectly!

https://kayii.goe.land/notice/A3lpVNFk4uTvuc2dM0

**Comment by kalvn** [comment]
v3 is out :)
