### ISSUE TITLE
Not compatible with Shaarli 11.1

### ISSUE THREAD

**Issue by MagicFab** [kalvn/shaarli2mastodon#17]
I recently upgraded to Shaarli 11.1 (under PHP 7.4.15) and noticed enabling shaarli2mastodon results in Shaarli only displaying a blank page.

`rm -r shaarli2mastodon/` under the `plugins` directory restores Shaarli.

**Comment by MagicFab** [comment]
Some more info, from the `error.log` file:

```
[fcgid:warn] [pid 416342:tid 3655431177984] [client IPADDRESS:46092] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Class 'Shaarli\\Render\\TemplatePage' not found in /var/www/shaarli/plugins/shaarli2mastodon/shaarli2mastodon.php:51, referer: https://mydomain.com/shaarli/?
[fcgid:warn] [pid 416342:tid 3655431177984] [client IPADDRESS:46092] mod_fcgid: stderr: Stack trace:, referer: https://mydomain.com/shaarli/?
[fcgid:warn] [pid 416342:tid 3655431177984] [client IPADDRESS:46092] mod_fcgid: stderr: #0 [internal function]: hook_shaarli2mastodon_render_includes(Array, Object(Shaarli\\Config\\ConfigManager)), referer: https://mydomain.com/shaarli/?
[fcgid:warn] [pid 416342:tid 3655431177984] [client IPADDRESS:46092] mod_fcgid: stderr: #1 /var/www/shaarli/application/plugin/PluginManager.php(115): call_user_func('hook_shaarli2ma...', Array, Object(Shaarli\\Config\\ConfigManager)), referer: https://mydomain.com/shaarli/?
[fcgid:warn] [pid 416342:tid 3655431177984] [client IPADDRESS:46092] mod_fcgid: stderr: #2 /var/www/shaarli/index.php(574): Shaarli\\Plugin\\PluginManager->executeHooks('render_includes', Array, Array), referer: https://mydomain.com/shaarli/?
[fcgid:warn] [pid 416342:tid 3655431177984] [client IPADDRESS:46092] mod_fcgid: stderr: #3 /var/www/shaarli/index.php(1953): renderPage(Object(Shaarli\\Config\\ConfigManager), Object(Shaarli\\Plugin\\PluginManager), Object(Shaarli\\Bookmark\\LinkDB), Object(Shaarli\\History), Object(Shaarli\\Security\\SessionManager), Object(Shaarli\\Security\\LoginManager)), referer: https://mydomain.com/shaarli/?
[fcgid:warn] [pid 416342:tid 3655431177984] [client IPADDRESS:46092] mod_fcgid: stderr: #4 {main}, referer: https://mydomain.com/shaarli/?
[fcgid:warn] [pid 416342:tid 3655431177984] [client IPADDRESS:46092] mod_fcgid: stderr:   thrown in /var/www/shaarli/plugins/shaarli2mastodon/shaarli2mastodon.php on line 51, referer: https://mydomain.com/shaarli/?
```

**Comment by kalvn** [comment]
What version of the extension are you using? The last one? Could be that the jump to support Shaarli v12.1 broke some things with older version of Shaarli. 

Would updating Shaarli to the latest version be a possibility for you?

**Comment by MagicFab** [comment]
> What version of the extension are you using? The last one? Could be that the jump to support Shaarli v12.1 broke some things with older version of Shaarli.

I tried using the last one.

> Would updating Shaarli to the latest version be a possibility for you?

Unfortunately, that's not working either:
https://github.com/shaarli/Shaarli/issues/1861

**Comment by MagicFab** [comment]
I've since installed Sharli 0.12.1 from scratch and reimported my data.
I had to reconfigure the plugin after re-generating the API key, averything works now, including re-publishing after editing.

**Comment by kalvn** [comment]
Alright, glad to hear that :)

I usually try to ensure the plugin works with the last version of Shaarli but sometimes new adaptations can break it for older versions. Ideally, the best is to have everything up to date.
