### ISSUE TITLE
Activating this plugin prevents shaarli from loading

### ISSUE THREAD

**Issue by Riduidel** [kalvn/shaarli2mastodon#18]
I've downloaded the latest v3.0.0 version to use with Shaarli 0.12.1

When I activate this plugin, I get the following error in apache logs

```
[Thu Nov 03 07:20:41.947608 2022] [php:error] [pid 4221] [client 192.168.0.254:51964] 
PHP Fatal error:  Uncaught Error: Class "Shaarli\\Render\\TemplatePage" not found in /var/www/html/Shaarli/plugins/shaarli2mastodon/shaarli2mastodon.php:51
Stack trace:
#0 [internal function]: hook_shaarli2mastodon_render_includes()
#1 /var/www/html/Shaarli/application/plugin/PluginManager.php(115): call_user_func()
#2 /var/www/html/Shaarli/index.php(574): Shaarli\\Plugin\\PluginManager->executeHooks()
#3 /var/www/html/Shaarli/index.php(1953): renderPage()
#4 {main}
thrown in /var/www/html/Shaarli/plugins/shaarli2mastodon/shaarli2mastodon.php on line 51, 
referer: https://nicolas-delsaux.hd.free.fr/Shaarli/?do=pluginadmin
```

And Shaarli UI doesn't shows up

**Comment by kalvn** [comment]
That is weird, the class does exist in Shaarli 0.12.1 : https://github.com/shaarli/Shaarli/blob/v0.12.1/application/render/TemplatePage.php

Can you check if this file exists in your server?

**Comment by Riduidel** [comment]
Crazily enough (or absolutly logically, depending upon your point of view), this file doesn't exist on my machine

```
pi@raspberrypi:/var/www/html/Shaarli $ ls application/render/
PageBuilder.php  ThemeUtils.php
```

What is even funnier is that I downloaded the file yesterday from Shaarli releases page ...
Well, I think I did, but it seems like Ansible didn't download everything, cause the file is available in Shaarli release ZIP. So the bug is on my side.

**Comment by kalvn** [comment]
That is indeed unusual, but I'm glad it's now sorted out :)
