### ISSUE TITLE
Allow the use of content warnings

### ISSUE THREAD

**Issue by Aldarone** [kalvn/shaarli2mastodon#2]
A shaarlink can feature a pretty long comment, which, in turn can become hard to read on mastodon.

This problem can be solved with the use of the native Content Warning feature of Mastodon. It would require an optional MASTODON_CW_FORMAT which would be an empty string by default and accept the same format tags as MASTODON_TOOT_FORMAT.

When this option is filled up, the plugin would put its formatted content in the mastodon Content Warning field.

As for the length issues that may rise by having two places to check instead of one, Mastodon considers the length of a toot as being [CW field length] + [Toot field length] so it should not be much of a hassle to deal with.

And for the use case, consider the readability of these example posts : 

MASTODON_TOOT_FORMAT : `${title}\n\n${description}\n\n-- ${url}\n\n${tags} #shaarlien`
![capture d ecran_2017-11-11_08-53-47](https://user-images.githubusercontent.com/2682011/32687493-e800c8ea-c6bd-11e7-88b3-bcfe68574968.png)

MASTODON_CW_FORMAT : `${title}`
MASTODON_TOOT_FORMAT : `${description}\n\n-- ${url}\n\n${tags} #shaarlien`
![capture d ecran_2017-11-11_08-56-42](https://user-images.githubusercontent.com/2682011/32687518-513ab8b6-c6be-11e7-99f2-65b625be94bf.png)

**Comment by kalvn** [comment]
That's a good idea, I'll consider it. Thanks for the very good description.

**Comment by kalvn** [comment]
This is now available in the last beta version : https://github.com/kalvn/shaarli2mastodon/releases/tag/v3.0.0-beta1

Would you like to give a try and let me know if it works as expected?

**Comment by kalvn** [comment]
v3 is out :)
