### ISSUE TITLE
Tags with accented characters (such as é and á) issue

### ISSUE THREAD

**Issue by alexisju** [kalvn/shaarli2mastodon#3]
Tags with accented characters (such as é and à) issue are published on Mastodon without these characters (i.e. #éléphant is published #lphant)

**Comment by kalvn** [comment]
Indeed, that's because a lot of characters are not valid for tags. I'll have a look precisely which characters are allowed and I'll adapt the regex.

**Comment by Draky50110** [comment]
Hello.

Same problem here with the french word "icône" spelled "icne" on Mastodon.

Source : https://gilles.wittezaele.fr/liens/?xY3YtQ
Result : https://mamot.fr/@ParigotManchot/99665721843326402

The shaarli2twitter addon has no problem with this word.

**Comment by kalvn** [comment]
This commit should fix the issue: https://github.com/kalvn/shaarli2mastodon/commit/f293ee362f6e9a93d7ed2bffc7c0daad861a051b
