### ISSUE TITLE
Notice Undefined index after form validation

### ISSUE THREAD

**Issue by opitux** [kalvn/shaarli2mastodon#4]
Hello,

Thank you very much for this plugin.
It works perfectly :)

I just have a little problem when I add a link. It is well inserted in Mastodon but I have the following message (just before the pop-up closes):

```
Notice: Undefined index: client_name in /path/to/shaarli/plugins/shaarli2mastodon/Mastodon/Mastodon.php on line 66

Notice: Undefined index: website /path/to/shaarli/plugins/shaarli2mastodon/Mastodon/Mastodon.php on line 67
```
Nothing blocking however

Edit : I'm on shaarli 0.9.2

**Comment by kalvn** [comment]
Hi, thanks for your feedback :)

The last commit https://github.com/kalvn/shaarli2mastodon/commit/bbe0e45284b0f00d20443f8d4947c45b739f3bcb should fix this issue.
