### ISSUE TITLE
Allow "Publish to Mastodon" option in link edition too

### ISSUE THREAD

**Issue by MagicFab** [kalvn/shaarli2mastodon#6]
When posting from the "Shaare link" button, an checkbox to "Publish to Mastodon" is available.

It would be useful to also have that box when editing a link in Shaarli, so the link can be published again.

**Comment by kalvn** [comment]
This is now possible with the latest beta release: https://github.com/kalvn/shaarli2mastodon/releases/tag/v3.0.0-beta2

Feel free to take a look :)

If I see no issues in the coing days, I'll release it as a final version.

**Comment by kalvn** [comment]
v3 is out :)
