### ISSUE TITLE
Use namespaces for future Shaarli v0.11

### ISSUE THREAD

**Issue by ArthurHoaro** [kalvn/shaarli2mastodon#8]
There is a breaking change for all plugins in Shaarli future release due to the introduction of namespaces.

See https://github.com/ArthurHoaro/shaarli2twitter/commit/c05d044bef8a4bcf4beee6e10eecec970dccf4c0

Shaarli v0.11.0 won't be released anytime soon at its current pace of development, but the plugin isn't currently compatible with the `master` branch. Maybe you should release the current state of this repo while it's compatible with v0.10.x.

**Comment by kalvn** [comment]
Thanks for pointing that out! I didn't even remember that I didn't made a proper release yet.

That's now done. I'll start adding namespaces for this plugin and the few others I have.
