### ISSUE TITLE
Erreur "class router"

### ISSUE THREAD

**Issue by Draky50110** [kalvn/shaarli2mastodon#9]
Hello.

Sur Shaarli 0.10.4 et en PHP 7.3.9 j'ai cette erreur 👍 

>  Fatal error: Cannot declare class Router, because the name is already in use in /home/XXX/liens/application/Router.php on line 8

**Comment by kalvn** [comment]
Hi @Draky50110 looks like you are using the wrong version. If you use Shaarli lower than v0.11.X you need to use shaarli2mastodon v1.0.0.

**Comment by Draky50110** [comment]
Ok, failed to update Shaarli, thanks !
